///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_RecycleBinClear
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Ranorex_RecycleBinClearRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
    [RepositoryFolder("6e6f1168-b64e-4c94-a6f2-0b23f5cf2305")]
    public partial class Ranorex_RecycleBinClearRepository : RepoGenBaseFolder
    {
        static Ranorex_RecycleBinClearRepository instance = new Ranorex_RecycleBinClearRepository();
        Ranorex_RecycleBinClearRepositoryFolders.Form201408271000RanorexAutomatedDAppFolder _form201408271000ranorexautomatedd;
        Ranorex_RecycleBinClearRepositoryFolders.ExplorerAppFolder _explorer;
        Ranorex_RecycleBinClearRepositoryFolders.ЭтотКомпьютерAppFolder _этоткомпьютер;
        Ranorex_RecycleBinClearRepositoryFolders.КорзинаAppFolder _корзина;
        Ranorex_RecycleBinClearRepositoryFolders.УдалитьФайлAppFolder _удалитьфайл;
        Ranorex_RecycleBinClearRepositoryFolders.Explorer1AppFolder _explorer1;

        /// <summary>
        /// Gets the singleton class instance representing the Ranorex_RecycleBinClearRepository element repository.
        /// </summary>
        [RepositoryFolder("6e6f1168-b64e-4c94-a6f2-0b23f5cf2305")]
        public static Ranorex_RecycleBinClearRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Ranorex_RecycleBinClearRepository() 
            : base("Ranorex_RecycleBinClearRepository", "/", null, 0, false, "6e6f1168-b64e-4c94-a6f2-0b23f5cf2305", ".\\RepositoryImages\\Ranorex_RecycleBinClearRepository6e6f1168.rximgres")
        {
            _form201408271000ranorexautomatedd = new Ranorex_RecycleBinClearRepositoryFolders.Form201408271000RanorexAutomatedDAppFolder(this);
            _explorer = new Ranorex_RecycleBinClearRepositoryFolders.ExplorerAppFolder(this);
            _этоткомпьютер = new Ranorex_RecycleBinClearRepositoryFolders.ЭтотКомпьютерAppFolder(this);
            _корзина = new Ranorex_RecycleBinClearRepositoryFolders.КорзинаAppFolder(this);
            _удалитьфайл = new Ranorex_RecycleBinClearRepositoryFolders.УдалитьФайлAppFolder(this);
            _explorer1 = new Ranorex_RecycleBinClearRepositoryFolders.Explorer1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6e6f1168-b64e-4c94-a6f2-0b23f5cf2305")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Form201408271000RanorexAutomatedD folder.
        /// </summary>
        [RepositoryFolder("9d24cff2-21ac-480d-afd9-0087e6757155")]
        public virtual Ranorex_RecycleBinClearRepositoryFolders.Form201408271000RanorexAutomatedDAppFolder Form201408271000RanorexAutomatedD
        {
            get { return _form201408271000ranorexautomatedd; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("a7cf6def-380c-4a73-bd23-7e0184272250")]
        public virtual Ranorex_RecycleBinClearRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The ЭтотКомпьютер folder.
        /// </summary>
        [RepositoryFolder("0d60a0f4-88fa-46ee-bc40-7f3340e65b7e")]
        public virtual Ranorex_RecycleBinClearRepositoryFolders.ЭтотКомпьютерAppFolder ЭтотКомпьютер
        {
            get { return _этоткомпьютер; }
        }

        /// <summary>
        /// The Корзина folder.
        /// </summary>
        [RepositoryFolder("c3c37233-d0fc-4699-8eec-f0ac9924d963")]
        public virtual Ranorex_RecycleBinClearRepositoryFolders.КорзинаAppFolder Корзина
        {
            get { return _корзина; }
        }

        /// <summary>
        /// The УдалитьФайл folder.
        /// </summary>
        [RepositoryFolder("f1670e86-f330-434f-9064-10f6bf1ccb9f")]
        public virtual Ranorex_RecycleBinClearRepositoryFolders.УдалитьФайлAppFolder УдалитьФайл
        {
            get { return _удалитьфайл; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("848bc6f1-3512-4e5e-8758-05cae44edcd6")]
        public virtual Ranorex_RecycleBinClearRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
    public partial class Ranorex_RecycleBinClearRepositoryFolders
    {
        /// <summary>
        /// The Form201408271000RanorexAutomatedDAppFolder folder.
        /// </summary>
        [RepositoryFolder("9d24cff2-21ac-480d-afd9-0087e6757155")]
        public partial class Form201408271000RanorexAutomatedDAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element246526080Info;
            RepoItemInfo _clientInfo;

            /// <summary>
            /// Creates a new Form201408271000RanorexAutomatedD  folder.
            /// </summary>
            public Form201408271000RanorexAutomatedDAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form201408271000RanorexAutomatedD", "/form[@title~'^2014\\ 08\\ 27\\ 10\\ 00\\ Ranorex\\ ']", parentFolder, 30000, null, true, "9d24cff2-21ac-480d-afd9-0087e6757155", "")
            {
                _element246526080Info = new RepoItemInfo(this, "Element246526080", "element[@controlid='246526080']", 30000, null, "3fa22a0c-b442-4fd0-b8a0-ebcf9583f0ea");
                _clientInfo = new RepoItemInfo(this, "Client", "container[@accessiblename='Google Chrome']/container[2]/container[3]", 30000, null, "aad0336b-5813-491a-86f1-05e7711c44f3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9d24cff2-21ac-480d-afd9-0087e6757155")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9d24cff2-21ac-480d-afd9-0087e6757155")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element246526080 item.
            /// </summary>
            [RepositoryItem("3fa22a0c-b442-4fd0-b8a0-ebcf9583f0ea")]
            public virtual Ranorex.Unknown Element246526080
            {
                get
                {
                    return _element246526080Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element246526080 item info.
            /// </summary>
            [RepositoryItemInfo("3fa22a0c-b442-4fd0-b8a0-ebcf9583f0ea")]
            public virtual RepoItemInfo Element246526080Info
            {
                get
                {
                    return _element246526080Info;
                }
            }

            /// <summary>
            /// The Client item.
            /// </summary>
            [RepositoryItem("aad0336b-5813-491a-86f1-05e7711c44f3")]
            public virtual Ranorex.Container Client
            {
                get
                {
                    return _clientInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client item info.
            /// </summary>
            [RepositoryItemInfo("aad0336b-5813-491a-86f1-05e7711c44f3")]
            public virtual RepoItemInfo ClientInfo
            {
                get
                {
                    return _clientInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("a7cf6def-380c-4a73-bd23-7e0184272250")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            Ranorex_RecycleBinClearRepositoryFolders.РаботающиеПриложенияFolder _работающиеприложения;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "a7cf6def-380c-4a73-bd23-7e0184272250", "")
            {
                _работающиеприложения = new Ranorex_RecycleBinClearRepositoryFolders.РаботающиеПриложенияFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a7cf6def-380c-4a73-bd23-7e0184272250")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a7cf6def-380c-4a73-bd23-7e0184272250")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The РаботающиеПриложения folder.
            /// </summary>
            [RepositoryFolder("0721c1a8-b3a6-4720-b08f-537ca14c8876")]
            public virtual Ranorex_RecycleBinClearRepositoryFolders.РаботающиеПриложенияFolder РаботающиеПриложения
            {
                get { return _работающиеприложения; }
            }
        }

        /// <summary>
        /// The РаботающиеПриложенияFolder folder.
        /// </summary>
        [RepositoryFolder("0721c1a8-b3a6-4720-b08f-537ca14c8876")]
        public partial class РаботающиеПриложенияFolder : RepoGenBaseFolder
        {
            RepoItemInfo _проводникInfo;
            RepoItemInfo _button201408271000ranorexautomatedInfo;
            RepoItemInfo _ranorexrecyclebinclearranorexstudioInfo;

            /// <summary>
            /// Creates a new РаботающиеПриложения  folder.
            /// </summary>
            public РаботающиеПриложенияFolder(RepoGenBaseFolder parentFolder) :
                    base("РаботающиеПриложения", "container[@controlid='40965']//toolbar[@accessiblename='Работающие приложения']", parentFolder, 30000, null, false, "0721c1a8-b3a6-4720-b08f-537ca14c8876", "")
            {
                _проводникInfo = new RepoItemInfo(this, "Проводник", "button[@accessiblename='Проводник']", 30000, null, "d04cdea8-3851-4ba1-b7d3-fa98329f280a");
                _button201408271000ranorexautomatedInfo = new RepoItemInfo(this, "Button201408271000RanorexAutomated", "button[@accessiblename~'^2014\\ 08\\ 27\\ 10\\ 00\\ Ranorex\\ ']", 30000, null, "6f138abf-413d-40d1-95fb-de92eaf80268");
                _ranorexrecyclebinclearranorexstudioInfo = new RepoItemInfo(this, "RanorexRecycleBinClearRanorexStudio", "button[@accessiblename~'^Ranorex_RecycleBinClear\\ -']", 30000, null, "6601a938-7bea-47b1-a036-b323e2a9327f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0721c1a8-b3a6-4720-b08f-537ca14c8876")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0721c1a8-b3a6-4720-b08f-537ca14c8876")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Проводник item.
            /// </summary>
            [RepositoryItem("d04cdea8-3851-4ba1-b7d3-fa98329f280a")]
            public virtual Ranorex.Button Проводник
            {
                get
                {
                    return _проводникInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Проводник item info.
            /// </summary>
            [RepositoryItemInfo("d04cdea8-3851-4ba1-b7d3-fa98329f280a")]
            public virtual RepoItemInfo ПроводникInfo
            {
                get
                {
                    return _проводникInfo;
                }
            }

            /// <summary>
            /// The Button201408271000RanorexAutomated item.
            /// </summary>
            [RepositoryItem("6f138abf-413d-40d1-95fb-de92eaf80268")]
            public virtual Ranorex.Button Button201408271000RanorexAutomated
            {
                get
                {
                    return _button201408271000ranorexautomatedInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button201408271000RanorexAutomated item info.
            /// </summary>
            [RepositoryItemInfo("6f138abf-413d-40d1-95fb-de92eaf80268")]
            public virtual RepoItemInfo Button201408271000RanorexAutomatedInfo
            {
                get
                {
                    return _button201408271000ranorexautomatedInfo;
                }
            }

            /// <summary>
            /// The RanorexRecycleBinClearRanorexStudio item.
            /// </summary>
            [RepositoryItem("6601a938-7bea-47b1-a036-b323e2a9327f")]
            public virtual Ranorex.Button RanorexRecycleBinClearRanorexStudio
            {
                get
                {
                    return _ranorexrecyclebinclearranorexstudioInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RanorexRecycleBinClearRanorexStudio item info.
            /// </summary>
            [RepositoryItemInfo("6601a938-7bea-47b1-a036-b323e2a9327f")]
            public virtual RepoItemInfo RanorexRecycleBinClearRanorexStudioInfo
            {
                get
                {
                    return _ranorexrecyclebinclearranorexstudioInfo;
                }
            }
        }

        /// <summary>
        /// The ЭтотКомпьютерAppFolder folder.
        /// </summary>
        [RepositoryFolder("0d60a0f4-88fa-46ee-bc40-7f3340e65b7e")]
        public partial class ЭтотКомпьютерAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pageupInfo;
            RepoItemInfo _someindicatorInfo;
            RepoItemInfo _корзинаInfo;
            RepoItemInfo _очиститькорзинуInfo;
            RepoItemInfo _folderlayoutcontainerInfo;
            RepoItemInfo _tree100Info;

            /// <summary>
            /// Creates a new ЭтотКомпьютер  folder.
            /// </summary>
            public ЭтотКомпьютерAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ЭтотКомпьютер", "/form[@title='Этот компьютер']", parentFolder, 30000, null, true, "0d60a0f4-88fa-46ee-bc40-7f3340e65b7e", "")
            {
                _pageupInfo = new RepoItemInfo(this, "PageUp", "element[@class='ShellTabWindowClass']//tree[@controlid='100']/scrollbar[@style='Vertical']/button[@text='PageUp']", 30000, null, "d402a5a3-89d3-4957-a935-94d8cae59c8b");
                _someindicatorInfo = new RepoItemInfo(this, "SomeIndicator", "element[@class='ShellTabWindowClass']//tree[@controlid='100']/scrollbar[@style='Vertical']/indicator", 30000, null, "4d60d2db-eb21-4a82-9a8b-af4d38a8512d");
                _корзинаInfo = new RepoItemInfo(this, "Корзина", "element[@class='ShellTabWindowClass']/?/?/container[@class='DirectUIHWND']/element[2]/?/?/tree[@controlid='100']/?/?/treeitem[@text='Корзина']", 30000, null, "c401f2bc-fcb0-4bc8-a96c-edfa6fa03734");
                _очиститькорзинуInfo = new RepoItemInfo(this, "ОчиститьКорзину", "element[3]//container[@accessiblename='Нижняя лента']/?/?/container[@accessiblename='Управление']/toolbar[@accessiblename='Управление']/button[@accessiblename='Очистить корзину']", 30000, null, "6d2e35f8-4cda-4f2e-ae86-a09b20ef702a");
                _folderlayoutcontainerInfo = new RepoItemInfo(this, "FolderLayoutContainer", "element[@class='ShellTabWindowClass']//container[@automationid='FolderLayoutContainer']", 30000, null, "e6df6bc6-7afb-4d6c-824b-6c4aaa463913");
                _tree100Info = new RepoItemInfo(this, "Tree100", "element[@class='ShellTabWindowClass']/?/?/container[@class='DirectUIHWND']/element[2]/?/?/tree[@controlid='100']", 30000, null, "4c334a05-ba26-4bec-9eb3-14328192e296");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0d60a0f4-88fa-46ee-bc40-7f3340e65b7e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0d60a0f4-88fa-46ee-bc40-7f3340e65b7e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PageUp item.
            /// </summary>
            [RepositoryItem("d402a5a3-89d3-4957-a935-94d8cae59c8b")]
            public virtual Ranorex.Button PageUp
            {
                get
                {
                    return _pageupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PageUp item info.
            /// </summary>
            [RepositoryItemInfo("d402a5a3-89d3-4957-a935-94d8cae59c8b")]
            public virtual RepoItemInfo PageUpInfo
            {
                get
                {
                    return _pageupInfo;
                }
            }

            /// <summary>
            /// The SomeIndicator item.
            /// </summary>
            [RepositoryItem("4d60d2db-eb21-4a82-9a8b-af4d38a8512d")]
            public virtual Ranorex.Indicator SomeIndicator
            {
                get
                {
                    return _someindicatorInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The SomeIndicator item info.
            /// </summary>
            [RepositoryItemInfo("4d60d2db-eb21-4a82-9a8b-af4d38a8512d")]
            public virtual RepoItemInfo SomeIndicatorInfo
            {
                get
                {
                    return _someindicatorInfo;
                }
            }

            /// <summary>
            /// The Корзина item.
            /// </summary>
            [RepositoryItem("c401f2bc-fcb0-4bc8-a96c-edfa6fa03734")]
            public virtual Ranorex.TreeItem Корзина
            {
                get
                {
                    return _корзинаInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Корзина item info.
            /// </summary>
            [RepositoryItemInfo("c401f2bc-fcb0-4bc8-a96c-edfa6fa03734")]
            public virtual RepoItemInfo КорзинаInfo
            {
                get
                {
                    return _корзинаInfo;
                }
            }

            /// <summary>
            /// The ОчиститьКорзину item.
            /// </summary>
            [RepositoryItem("6d2e35f8-4cda-4f2e-ae86-a09b20ef702a")]
            public virtual Ranorex.Button ОчиститьКорзину
            {
                get
                {
                    return _очиститькорзинуInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ОчиститьКорзину item info.
            /// </summary>
            [RepositoryItemInfo("6d2e35f8-4cda-4f2e-ae86-a09b20ef702a")]
            public virtual RepoItemInfo ОчиститьКорзинуInfo
            {
                get
                {
                    return _очиститькорзинуInfo;
                }
            }

            /// <summary>
            /// The FolderLayoutContainer item.
            /// </summary>
            [RepositoryItem("e6df6bc6-7afb-4d6c-824b-6c4aaa463913")]
            public virtual Ranorex.Container FolderLayoutContainer
            {
                get
                {
                    return _folderlayoutcontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The FolderLayoutContainer item info.
            /// </summary>
            [RepositoryItemInfo("e6df6bc6-7afb-4d6c-824b-6c4aaa463913")]
            public virtual RepoItemInfo FolderLayoutContainerInfo
            {
                get
                {
                    return _folderlayoutcontainerInfo;
                }
            }

            /// <summary>
            /// The Tree100 item.
            /// </summary>
            [RepositoryItem("4c334a05-ba26-4bec-9eb3-14328192e296")]
            public virtual Ranorex.Tree Tree100
            {
                get
                {
                    return _tree100Info.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Tree100 item info.
            /// </summary>
            [RepositoryItemInfo("4c334a05-ba26-4bec-9eb3-14328192e296")]
            public virtual RepoItemInfo Tree100Info
            {
                get
                {
                    return _tree100Info;
                }
            }
        }

        /// <summary>
        /// The КорзинаAppFolder folder.
        /// </summary>
        [RepositoryFolder("c3c37233-d0fc-4699-8eec-f0ac9924d963")]
        public partial class КорзинаAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _корзинаInfo;
            RepoItemInfo _очиститькорзинуInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Корзина  folder.
            /// </summary>
            public КорзинаAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Корзина", "/form[@title='Корзина']", parentFolder, 30000, null, true, "c3c37233-d0fc-4699-8eec-f0ac9924d963", "")
            {
                _корзинаInfo = new RepoItemInfo(this, "Корзина", "element[@class='ShellTabWindowClass']/?/?/container[@class='DirectUIHWND']/element[1]/?/?/tree[@controlid='100']/?/?/treeitem[@text='Корзина']", 30000, null, "1e56cb29-0660-49d9-9a81-f0a8dbaff004");
                _очиститькорзинуInfo = new RepoItemInfo(this, "ОчиститьКорзину", "element[3]//container[@accessiblename='Нижняя лента']/?/?/container[@accessiblename='Управление']/toolbar[@accessiblename='Управление']/button[@accessiblename='Очистить корзину']", 30000, null, "2c157560-9f42-48e6-8146-1134e265344d");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@automationid='Close']", 30000, null, "b8563d93-b5a1-4931-9db2-8a8132022623");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c3c37233-d0fc-4699-8eec-f0ac9924d963")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c3c37233-d0fc-4699-8eec-f0ac9924d963")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Корзина item.
            /// </summary>
            [RepositoryItem("1e56cb29-0660-49d9-9a81-f0a8dbaff004")]
            public virtual Ranorex.TreeItem Корзина
            {
                get
                {
                    return _корзинаInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Корзина item info.
            /// </summary>
            [RepositoryItemInfo("1e56cb29-0660-49d9-9a81-f0a8dbaff004")]
            public virtual RepoItemInfo КорзинаInfo
            {
                get
                {
                    return _корзинаInfo;
                }
            }

            /// <summary>
            /// The ОчиститьКорзину item.
            /// </summary>
            [RepositoryItem("2c157560-9f42-48e6-8146-1134e265344d")]
            public virtual Ranorex.Button ОчиститьКорзину
            {
                get
                {
                    return _очиститькорзинуInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ОчиститьКорзину item info.
            /// </summary>
            [RepositoryItemInfo("2c157560-9f42-48e6-8146-1134e265344d")]
            public virtual RepoItemInfo ОчиститьКорзинуInfo
            {
                get
                {
                    return _очиститькорзинуInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("b8563d93-b5a1-4931-9db2-8a8132022623")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("b8563d93-b5a1-4931-9db2-8a8132022623")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The УдалитьФайлAppFolder folder.
        /// </summary>
        [RepositoryFolder("f1670e86-f330-434f-9064-10f6bf1ccb9f")]
        public partial class УдалитьФайлAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonдаInfo;

            /// <summary>
            /// Creates a new УдалитьФайл  folder.
            /// </summary>
            public УдалитьФайлAppFolder(RepoGenBaseFolder parentFolder) :
                    base("УдалитьФайл", "/form[@title='Удалить файл']", parentFolder, 30000, null, true, "f1670e86-f330-434f-9064-10f6bf1ccb9f", "")
            {
                _buttonдаInfo = new RepoItemInfo(this, "ButtonДа", "button[@text='Д&а']", 30000, null, "7eb89b31-8755-448a-893f-a479acc42fbf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f1670e86-f330-434f-9064-10f6bf1ccb9f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f1670e86-f330-434f-9064-10f6bf1ccb9f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonДа item.
            /// </summary>
            [RepositoryItem("7eb89b31-8755-448a-893f-a479acc42fbf")]
            public virtual Ranorex.Button ButtonДа
            {
                get
                {
                    return _buttonдаInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonДа item info.
            /// </summary>
            [RepositoryItemInfo("7eb89b31-8755-448a-893f-a479acc42fbf")]
            public virtual RepoItemInfo ButtonДаInfo
            {
                get
                {
                    return _buttonдаInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("848bc6f1-3512-4e5e-8758-05cae44edcd6")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "848bc6f1-3512-4e5e-8758-05cae44edcd6", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@controlid='1']", 30000, null, "33aa6677-f0f0-4eb9-8228-8b69669a3018");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("848bc6f1-3512-4e5e-8758-05cae44edcd6")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("848bc6f1-3512-4e5e-8758-05cae44edcd6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("33aa6677-f0f0-4eb9-8228-8b69669a3018")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("33aa6677-f0f0-4eb9-8228-8b69669a3018")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}