///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_RecycleBinClear
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("cf661a46-5bfa-40d5-900f-5cb680a0a073", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Ranorex_RecycleBinClearRepository repository.
        /// </summary>
        public static Ranorex_RecycleBinClearRepository repo = Ranorex_RecycleBinClearRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.РаботающиеПриложения.Проводник' at 26;19.", repo.Explorer.РаботающиеПриложения.ПроводникInfo, new RecordItemIndex(0));
            repo.Explorer.РаботающиеПриложения.Проводник.Click("26;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ЭтотКомпьютер.PageUp' at 9;25.", repo.ЭтотКомпьютер.PageUpInfo, new RecordItemIndex(1));
            repo.ЭтотКомпьютер.PageUp.Click("9;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ЭтотКомпьютер.Корзина' at 16;11.", repo.ЭтотКомпьютер.КорзинаInfo, new RecordItemIndex(2));
            repo.ЭтотКомпьютер.Корзина.Click("16;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Корзина.ОчиститьКорзину' at 40;41.", repo.Корзина.ОчиститьКорзинуInfo, new RecordItemIndex(3));
            repo.Корзина.ОчиститьКорзину.Click("40;41");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'УдалитьФайл.ButtonДа' at 39;9.", repo.УдалитьФайл.ButtonДаInfo, new RecordItemIndex(4));
            repo.УдалитьФайл.ButtonДа.Click("39;9");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
