///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_CleanRecycleBin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Ranorex_CleanRecycleBinRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
    [RepositoryFolder("2b79d514-8317-4cc2-a66c-93df705c5984")]
    public partial class Ranorex_CleanRecycleBinRepository : RepoGenBaseFolder
    {
        static Ranorex_CleanRecycleBinRepository instance = new Ranorex_CleanRecycleBinRepository();
        Ranorex_CleanRecycleBinRepositoryFolders.ExplorerAppFolder _explorer;
        Ranorex_CleanRecycleBinRepositoryFolders.Explorer1AppFolder _explorer1;
        Ranorex_CleanRecycleBinRepositoryFolders.Explorer2AppFolder _explorer2;
        Ranorex_CleanRecycleBinRepositoryFolders.ЭтотКомпьютерAppFolder _этоткомпьютер;
        Ranorex_CleanRecycleBinRepositoryFolders.УдалитьФайлAppFolder _удалитьфайл;
        Ranorex_CleanRecycleBinRepositoryFolders.НовийTxtБлокнотAppFolder _новийtxtблокнот;
        Ranorex_CleanRecycleBinRepositoryFolders.NotepadAppFolder _notepad;

        /// <summary>
        /// Gets the singleton class instance representing the Ranorex_CleanRecycleBinRepository element repository.
        /// </summary>
        [RepositoryFolder("2b79d514-8317-4cc2-a66c-93df705c5984")]
        public static Ranorex_CleanRecycleBinRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Ranorex_CleanRecycleBinRepository() 
            : base("Ranorex_CleanRecycleBinRepository", "/", null, 0, false, "2b79d514-8317-4cc2-a66c-93df705c5984", ".\\RepositoryImages\\Ranorex_CleanRecycleBinRepository2b79d514.rximgres")
        {
            _explorer = new Ranorex_CleanRecycleBinRepositoryFolders.ExplorerAppFolder(this);
            _explorer1 = new Ranorex_CleanRecycleBinRepositoryFolders.Explorer1AppFolder(this);
            _explorer2 = new Ranorex_CleanRecycleBinRepositoryFolders.Explorer2AppFolder(this);
            _этоткомпьютер = new Ranorex_CleanRecycleBinRepositoryFolders.ЭтотКомпьютерAppFolder(this);
            _удалитьфайл = new Ranorex_CleanRecycleBinRepositoryFolders.УдалитьФайлAppFolder(this);
            _новийtxtблокнот = new Ranorex_CleanRecycleBinRepositoryFolders.НовийTxtБлокнотAppFolder(this);
            _notepad = new Ranorex_CleanRecycleBinRepositoryFolders.NotepadAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2b79d514-8317-4cc2-a66c-93df705c5984")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("526ae01d-4477-4737-ad5b-f6d96dea5abe")]
        public virtual Ranorex_CleanRecycleBinRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("2e90217d-3553-4f88-af4a-276266b97352")]
        public virtual Ranorex_CleanRecycleBinRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The Explorer2 folder.
        /// </summary>
        [RepositoryFolder("58cc51fc-d01b-472a-bbe6-809e1e4ef5c4")]
        public virtual Ranorex_CleanRecycleBinRepositoryFolders.Explorer2AppFolder Explorer2
        {
            get { return _explorer2; }
        }

        /// <summary>
        /// The ЭтотКомпьютер folder.
        /// </summary>
        [RepositoryFolder("3650ac97-3dc4-4e69-a6a0-45e63832d0fa")]
        public virtual Ranorex_CleanRecycleBinRepositoryFolders.ЭтотКомпьютерAppFolder ЭтотКомпьютер
        {
            get { return _этоткомпьютер; }
        }

        /// <summary>
        /// The УдалитьФайл folder.
        /// </summary>
        [RepositoryFolder("91145e47-209f-4748-be80-98f910d1986d")]
        public virtual Ranorex_CleanRecycleBinRepositoryFolders.УдалитьФайлAppFolder УдалитьФайл
        {
            get { return _удалитьфайл; }
        }

        /// <summary>
        /// The НовийTxtБлокнот folder.
        /// </summary>
        [RepositoryFolder("4258d0bd-e4f8-4c45-ae2d-522448c14f2d")]
        public virtual Ranorex_CleanRecycleBinRepositoryFolders.НовийTxtБлокнотAppFolder НовийTxtБлокнот
        {
            get { return _новийtxtблокнот; }
        }

        /// <summary>
        /// The Notepad folder.
        /// </summary>
        [RepositoryFolder("cf1240df-1978-451b-9baa-a4f7d37608cc")]
        public virtual Ranorex_CleanRecycleBinRepositoryFolders.NotepadAppFolder Notepad
        {
            get { return _notepad; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
    public partial class Ranorex_CleanRecycleBinRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("526ae01d-4477-4737-ad5b-f6d96dea5abe")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;
            RepoItemInfo _новийtxtInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "526ae01d-4477-4737-ad5b-f6d96dea5abe", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@controlid='1']", 30000, null, "36ff657f-04fd-4efb-9e9c-720f6dd38508");
                _новийtxtInfo = new RepoItemInfo(this, "НовийTxt", "?/?/list[@controlid='1']/listitem[@text='Новий.txt']", 30000, null, "c788c1b4-9cea-4e58-a64c-8b23e7c71e96");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("526ae01d-4477-4737-ad5b-f6d96dea5abe")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("526ae01d-4477-4737-ad5b-f6d96dea5abe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("36ff657f-04fd-4efb-9e9c-720f6dd38508")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("36ff657f-04fd-4efb-9e9c-720f6dd38508")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }

            /// <summary>
            /// The НовийTxt item.
            /// </summary>
            [RepositoryItem("c788c1b4-9cea-4e58-a64c-8b23e7c71e96")]
            public virtual Ranorex.ListItem НовийTxt
            {
                get
                {
                    return _новийtxtInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The НовийTxt item info.
            /// </summary>
            [RepositoryItemInfo("c788c1b4-9cea-4e58-a64c-8b23e7c71e96")]
            public virtual RepoItemInfo НовийTxtInfo
            {
                get
                {
                    return _новийtxtInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("2e90217d-3553-4f88-af4a-276266b97352")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _создатьInfo;
            RepoItemInfo _текстовыйдокументInfo;
            RepoItemInfo _удалитьInfo;
            RepoItemInfo _очиститькорзинуInfo;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/contextmenu[@processname='explorer']", parentFolder, 30000, null, true, "2e90217d-3553-4f88-af4a-276266b97352", "")
            {
                _создатьInfo = new RepoItemInfo(this, "Создать", "?/?/menuitem[@accessiblename='Создать']", 30000, null, "8416ba9e-e58d-4a5b-a492-5f53a7ab7f94");
                _текстовыйдокументInfo = new RepoItemInfo(this, "ТекстовыйДокумент", "?/?/menuitem[@accessiblename='Текстовый документ']", 30000, null, "ef940e04-c7d4-4504-aef3-9920d96ecacc");
                _удалитьInfo = new RepoItemInfo(this, "Удалить", "?/?/menuitem[@accessiblename='Удалить']", 30000, null, "310a56a7-29ec-4cee-a748-14cad6b3177e");
                _очиститькорзинуInfo = new RepoItemInfo(this, "ОчиститьКорзину", "?/?/menuitem[@accessiblename='Очистить корзину']", 30000, null, "beac096b-b2f8-451e-9018-f09580aa9a4b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2e90217d-3553-4f88-af4a-276266b97352")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2e90217d-3553-4f88-af4a-276266b97352")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Создать item.
            /// </summary>
            [RepositoryItem("8416ba9e-e58d-4a5b-a492-5f53a7ab7f94")]
            public virtual Ranorex.MenuItem Создать
            {
                get
                {
                    return _создатьInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Создать item info.
            /// </summary>
            [RepositoryItemInfo("8416ba9e-e58d-4a5b-a492-5f53a7ab7f94")]
            public virtual RepoItemInfo СоздатьInfo
            {
                get
                {
                    return _создатьInfo;
                }
            }

            /// <summary>
            /// The ТекстовыйДокумент item.
            /// </summary>
            [RepositoryItem("ef940e04-c7d4-4504-aef3-9920d96ecacc")]
            public virtual Ranorex.MenuItem ТекстовыйДокумент
            {
                get
                {
                    return _текстовыйдокументInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ТекстовыйДокумент item info.
            /// </summary>
            [RepositoryItemInfo("ef940e04-c7d4-4504-aef3-9920d96ecacc")]
            public virtual RepoItemInfo ТекстовыйДокументInfo
            {
                get
                {
                    return _текстовыйдокументInfo;
                }
            }

            /// <summary>
            /// The Удалить item.
            /// </summary>
            [RepositoryItem("310a56a7-29ec-4cee-a748-14cad6b3177e")]
            public virtual Ranorex.MenuItem Удалить
            {
                get
                {
                    return _удалитьInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Удалить item info.
            /// </summary>
            [RepositoryItemInfo("310a56a7-29ec-4cee-a748-14cad6b3177e")]
            public virtual RepoItemInfo УдалитьInfo
            {
                get
                {
                    return _удалитьInfo;
                }
            }

            /// <summary>
            /// The ОчиститьКорзину item.
            /// </summary>
            [RepositoryItem("beac096b-b2f8-451e-9018-f09580aa9a4b")]
            public virtual Ranorex.MenuItem ОчиститьКорзину
            {
                get
                {
                    return _очиститькорзинуInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ОчиститьКорзину item info.
            /// </summary>
            [RepositoryItemInfo("beac096b-b2f8-451e-9018-f09580aa9a4b")]
            public virtual RepoItemInfo ОчиститьКорзинуInfo
            {
                get
                {
                    return _очиститькорзинуInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer2AppFolder folder.
        /// </summary>
        [RepositoryFolder("58cc51fc-d01b-472a-bbe6-809e1e4ef5c4")]
        public partial class Explorer2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _проводникInfo;

            /// <summary>
            /// Creates a new Explorer2  folder.
            /// </summary>
            public Explorer2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer2", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "58cc51fc-d01b-472a-bbe6-809e1e4ef5c4", "")
            {
                _проводникInfo = new RepoItemInfo(this, "Проводник", "container[@controlid='40965']//toolbar[@accessiblename='Работающие приложения']/button[@accessiblename='Проводник']", 30000, null, "54fca69f-cb96-4c85-85f0-1c3befbeb47c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("58cc51fc-d01b-472a-bbe6-809e1e4ef5c4")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("58cc51fc-d01b-472a-bbe6-809e1e4ef5c4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Проводник item.
            /// </summary>
            [RepositoryItem("54fca69f-cb96-4c85-85f0-1c3befbeb47c")]
            public virtual Ranorex.Button Проводник
            {
                get
                {
                    return _проводникInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Проводник item info.
            /// </summary>
            [RepositoryItemInfo("54fca69f-cb96-4c85-85f0-1c3befbeb47c")]
            public virtual RepoItemInfo ПроводникInfo
            {
                get
                {
                    return _проводникInfo;
                }
            }
        }

        /// <summary>
        /// The ЭтотКомпьютерAppFolder folder.
        /// </summary>
        [RepositoryFolder("3650ac97-3dc4-4e69-a6a0-45e63832d0fa")]
        public partial class ЭтотКомпьютерAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _корзинаInfo;
            RepoItemInfo _корзина1Info;
            RepoItemInfo _propertyvalueInfo;
            RepoItemInfo _tree100Info;

            /// <summary>
            /// Creates a new ЭтотКомпьютер  folder.
            /// </summary>
            public ЭтотКомпьютерAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ЭтотКомпьютер", "/form[@title='Этот компьютер']", parentFolder, 30000, null, true, "3650ac97-3dc4-4e69-a6a0-45e63832d0fa", "")
            {
                _корзинаInfo = new RepoItemInfo(this, "Корзина", "element[@class='ShellTabWindowClass']/?/?/container[@class='DirectUIHWND']/element[2]/?/?/tree[@controlid='100']/?/?/treeitem[@text='Корзина']", 30000, null, "786ac6ab-cc27-4ff5-927e-bacb9f52cdc2");
                _корзина1Info = new RepoItemInfo(this, "Корзина1", "element[@class='ShellTabWindowClass']/?/?/container[@class='DirectUIHWND']/element[1]/?/?/tree[@controlid='100']/?/?/treeitem[@text='Корзина']", 30000, null, "44eda5d0-aecc-4a6e-bbb2-a6e5c887cd6e");
                _propertyvalueInfo = new RepoItemInfo(this, "PropertyValue", ".//container[@automationid='FolderLayoutContainer']/statusbar[@automationid='StatusBarModuleInner']/container[@automationid='System.StatusBarViewItemCount']/text[@automationid='PropertyValue']", 30000, null, "5b1e5c21-225a-4023-a0d6-ec8c0ad6efa1");
                _tree100Info = new RepoItemInfo(this, "Tree100", "element[@class='ShellTabWindowClass']/?/?/container[@class='DirectUIHWND']/element[2]/?/?/tree[@controlid='100']", 30000, null, "c8ebb7fc-cc3b-4727-b08c-0d8a84509c17");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3650ac97-3dc4-4e69-a6a0-45e63832d0fa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3650ac97-3dc4-4e69-a6a0-45e63832d0fa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Корзина item.
            /// </summary>
            [RepositoryItem("786ac6ab-cc27-4ff5-927e-bacb9f52cdc2")]
            public virtual Ranorex.TreeItem Корзина
            {
                get
                {
                    return _корзинаInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Корзина item info.
            /// </summary>
            [RepositoryItemInfo("786ac6ab-cc27-4ff5-927e-bacb9f52cdc2")]
            public virtual RepoItemInfo КорзинаInfo
            {
                get
                {
                    return _корзинаInfo;
                }
            }

            /// <summary>
            /// The Корзина1 item.
            /// </summary>
            [RepositoryItem("44eda5d0-aecc-4a6e-bbb2-a6e5c887cd6e")]
            public virtual Ranorex.TreeItem Корзина1
            {
                get
                {
                    return _корзина1Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Корзина1 item info.
            /// </summary>
            [RepositoryItemInfo("44eda5d0-aecc-4a6e-bbb2-a6e5c887cd6e")]
            public virtual RepoItemInfo Корзина1Info
            {
                get
                {
                    return _корзина1Info;
                }
            }

            /// <summary>
            /// The PropertyValue item.
            /// </summary>
            [RepositoryItem("5b1e5c21-225a-4023-a0d6-ec8c0ad6efa1")]
            public virtual Ranorex.Text PropertyValue
            {
                get
                {
                    return _propertyvalueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PropertyValue item info.
            /// </summary>
            [RepositoryItemInfo("5b1e5c21-225a-4023-a0d6-ec8c0ad6efa1")]
            public virtual RepoItemInfo PropertyValueInfo
            {
                get
                {
                    return _propertyvalueInfo;
                }
            }

            /// <summary>
            /// The Tree100 item.
            /// </summary>
            [RepositoryItem("c8ebb7fc-cc3b-4727-b08c-0d8a84509c17")]
            public virtual Ranorex.Tree Tree100
            {
                get
                {
                    return _tree100Info.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Tree100 item info.
            /// </summary>
            [RepositoryItemInfo("c8ebb7fc-cc3b-4727-b08c-0d8a84509c17")]
            public virtual RepoItemInfo Tree100Info
            {
                get
                {
                    return _tree100Info;
                }
            }
        }

        /// <summary>
        /// The УдалитьФайлAppFolder folder.
        /// </summary>
        [RepositoryFolder("91145e47-209f-4748-be80-98f910d1986d")]
        public partial class УдалитьФайлAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonдаInfo;

            /// <summary>
            /// Creates a new УдалитьФайл  folder.
            /// </summary>
            public УдалитьФайлAppFolder(RepoGenBaseFolder parentFolder) :
                    base("УдалитьФайл", "/form[@title='Удалить файл']", parentFolder, 30000, null, true, "91145e47-209f-4748-be80-98f910d1986d", "")
            {
                _buttonдаInfo = new RepoItemInfo(this, "ButtonДа", "button[@text='Д&а']", 30000, null, "107aef92-2c2f-46f5-95cb-5cc84f1e1d7d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("91145e47-209f-4748-be80-98f910d1986d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("91145e47-209f-4748-be80-98f910d1986d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonДа item.
            /// </summary>
            [RepositoryItem("107aef92-2c2f-46f5-95cb-5cc84f1e1d7d")]
            public virtual Ranorex.Button ButtonДа
            {
                get
                {
                    return _buttonдаInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonДа item info.
            /// </summary>
            [RepositoryItemInfo("107aef92-2c2f-46f5-95cb-5cc84f1e1d7d")]
            public virtual RepoItemInfo ButtonДаInfo
            {
                get
                {
                    return _buttonдаInfo;
                }
            }
        }

        /// <summary>
        /// The НовийTxtБлокнотAppFolder folder.
        /// </summary>
        [RepositoryFolder("4258d0bd-e4f8-4c45-ae2d-522448c14f2d")]
        public partial class НовийTxtБлокнотAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _файлInfo;
            RepoItemInfo _закрытьInfo;

            /// <summary>
            /// Creates a new НовийTxtБлокнот  folder.
            /// </summary>
            public НовийTxtБлокнотAppFolder(RepoGenBaseFolder parentFolder) :
                    base("НовийTxtБлокнот", "/form[@title='Новий.txt — Блокнот']", parentFolder, 30000, null, true, "4258d0bd-e4f8-4c45-ae2d-522448c14f2d", "")
            {
                _файлInfo = new RepoItemInfo(this, "Файл", "?/?/menuitem[@accessiblename='Файл']", 30000, null, "73cc03aa-824e-4b5e-b787-85e05ce3cecc");
                _закрытьInfo = new RepoItemInfo(this, "Закрыть", "?/?/button[@accessiblename='Закрыть']", 30000, null, "d9b102b4-f555-420c-b099-ef67d2e01154");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4258d0bd-e4f8-4c45-ae2d-522448c14f2d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4258d0bd-e4f8-4c45-ae2d-522448c14f2d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Файл item.
            /// </summary>
            [RepositoryItem("73cc03aa-824e-4b5e-b787-85e05ce3cecc")]
            public virtual Ranorex.MenuItem Файл
            {
                get
                {
                    return _файлInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Файл item info.
            /// </summary>
            [RepositoryItemInfo("73cc03aa-824e-4b5e-b787-85e05ce3cecc")]
            public virtual RepoItemInfo ФайлInfo
            {
                get
                {
                    return _файлInfo;
                }
            }

            /// <summary>
            /// The Закрыть item.
            /// </summary>
            [RepositoryItem("d9b102b4-f555-420c-b099-ef67d2e01154")]
            public virtual Ranorex.Button Закрыть
            {
                get
                {
                    return _закрытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Закрыть item info.
            /// </summary>
            [RepositoryItemInfo("d9b102b4-f555-420c-b099-ef67d2e01154")]
            public virtual RepoItemInfo ЗакрытьInfo
            {
                get
                {
                    return _закрытьInfo;
                }
            }
        }

        /// <summary>
        /// The NotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("cf1240df-1978-451b-9baa-a4f7d37608cc")]
        public partial class NotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _сохранитьctrlplussInfo;

            /// <summary>
            /// Creates a new Notepad  folder.
            /// </summary>
            public NotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Notepad", "/contextmenu[@processname='notepad']", parentFolder, 30000, null, true, "cf1240df-1978-451b-9baa-a4f7d37608cc", "")
            {
                _сохранитьctrlplussInfo = new RepoItemInfo(this, "СохранитьCTRLPlusS", "?/?/menuitem[@accessiblename='СохранитьCTRL+S']", 30000, null, "2e067b43-5635-459d-8bd4-9c5c75272452");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf1240df-1978-451b-9baa-a4f7d37608cc")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf1240df-1978-451b-9baa-a4f7d37608cc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The СохранитьCTRLPlusS item.
            /// </summary>
            [RepositoryItem("2e067b43-5635-459d-8bd4-9c5c75272452")]
            public virtual Ranorex.MenuItem СохранитьCTRLPlusS
            {
                get
                {
                    return _сохранитьctrlplussInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The СохранитьCTRLPlusS item info.
            /// </summary>
            [RepositoryItemInfo("2e067b43-5635-459d-8bd4-9c5c75272452")]
            public virtual RepoItemInfo СохранитьCTRLPlusSInfo
            {
                get
                {
                    return _сохранитьctrlplussInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}