///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_CleanRecycleBin
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("1cd8a4ae-5001-419a-9a3f-ef66b7c8e04a", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Ranorex_CleanRecycleBinRepository repository.
        /// </summary>
        public static Ranorex_CleanRecycleBinRepository repo = Ranorex_CleanRecycleBinRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Explorer.List1' at 213;151.", repo.Explorer.List1Info, new RecordItemIndex(0));
            repo.Explorer.List1.Click(System.Windows.Forms.MouseButtons.Right, "213;151");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.Создать' at 92;9.", repo.Explorer1.СоздатьInfo, new RecordItemIndex(1));
            repo.Explorer1.Создать.Click("92;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.ТекстовыйДокумент' at 69;2.", repo.Explorer1.ТекстовыйДокументInfo, new RecordItemIndex(2));
            repo.Explorer1.ТекстовыйДокумент.Click("69;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}Н{LShiftKey up}овий{Return}{Return}'.", new RecordItemIndex(3));
            Keyboard.Press("{LShiftKey down}Н{LShiftKey up}овий{Return}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}'.", new RecordItemIndex(4));
            Keyboard.Press("{LShiftKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Д{LShiftKey up}еякий{Space}текст{Space}'.", new RecordItemIndex(5));
            Keyboard.Press("Д{LShiftKey up}еякий{Space}текст{Space}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'який{Space}не{Space}має{Space}ніякого{Space}значення'.", new RecordItemIndex(6));
            Keyboard.Press("який{Space}не{Space}має{Space}ніякого{Space}значення");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'НовийTxtБлокнот.Файл' at 15;10.", repo.НовийTxtБлокнот.ФайлInfo, new RecordItemIndex(7));
            repo.НовийTxtБлокнот.Файл.Click("15;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Notepad.СохранитьCTRLPlusS' at 60;3.", repo.Notepad.СохранитьCTRLPlusSInfo, new RecordItemIndex(8));
            repo.Notepad.СохранитьCTRLPlusS.Click("60;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'НовийTxtБлокнот.Закрыть' at 28;12.", repo.НовийTxtБлокнот.ЗакрытьInfo, new RecordItemIndex(9));
            repo.НовийTxtБлокнот.Закрыть.Click("28;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Explorer.НовийTxt' at 28;55.", repo.Explorer.НовийTxtInfo, new RecordItemIndex(10));
            repo.Explorer.НовийTxt.Click(System.Windows.Forms.MouseButtons.Right, "28;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.Удалить' at 79;6.", repo.Explorer1.УдалитьInfo, new RecordItemIndex(11));
            repo.Explorer1.Удалить.Click("79;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer2.Проводник' at 25;23.", repo.Explorer2.ПроводникInfo, new RecordItemIndex(12));
            repo.Explorer2.Проводник.Click("25;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ЭтотКомпьютер.Tree100' at 100;104.", repo.ЭтотКомпьютер.Tree100Info, new RecordItemIndex(13));
            repo.ЭтотКомпьютер.Tree100.Click("100;104");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'ЭтотКомпьютер.Корзина1' at 37;6.", repo.ЭтотКомпьютер.Корзина1Info, new RecordItemIndex(14));
            repo.ЭтотКомпьютер.Корзина1.Click(System.Windows.Forms.MouseButtons.Right, "37;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer1.ОчиститьКорзину' at 105;5.", repo.Explorer1.ОчиститьКорзинуInfo, new RecordItemIndex(15));
            repo.Explorer1.ОчиститьКорзину.Click("105;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'УдалитьФайл.ButtonДа' at 32;14.", repo.УдалитьФайл.ButtonДаInfo, new RecordItemIndex(16));
            repo.УдалитьФайл.ButtonДа.Click("32;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Элементов: 0') on item 'ЭтотКомпьютер.PropertyValue'.", repo.ЭтотКомпьютер.PropertyValueInfo, new RecordItemIndex(17));
            Validate.Attribute(repo.ЭтотКомпьютер.PropertyValueInfo, "Text", "Элементов: 0");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
